NameError: name 'MONGODB_URL_KEY' is not defined

In [1]:
import os 

In [2]:
os.getenv('API_KEY')

'R63PKKPJKHWLYJLN'

In [5]:
a = os.getenv('MONGO_DB_URL')

In [6]:
a

'mongodb+srv://aryanro45:aryanrog45@test.iotfsde.mongodb.net/?retryWrites=true&w=majority&appName=test'

In [1]:
from sensor.utils.main_utils import read_yaml_file

In [3]:
file_path = 'C:\Sensor-Fault-Detection\config\schema.yaml'

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\KIIT\AppData\Local\Temp\ipykernel_19768\395110394.py:1: SyntaxWarning: invalid escape sequence '\S'
  file_path = 'C:\Sensor-Fault-Detection\config\schema.yaml'


In [5]:
schema_connfig = read_yaml_file(file_path=file_path)

In [7]:
len(schema_connfig['columns'])

164

In [8]:
from scipy.stats import ks_2samp

In [9]:
import numpy as np 

In [10]:
d1 = np.arange(10)
d2 = np.arange(10) 

In [11]:
d1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
d3 = np.arange(100,200)

In [16]:
test = ks_2samp(d1,d3)

In [17]:
test.pvalue

np.float64(4.2646072253826637e-14)

In [18]:
d3 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [27]:
import pandas as pd 

In [88]:
training_file_paTH=r"C:\Sensor-Fault-Detection\artifact\07_29_2024_15_02_42\data_ingestion\ingested\train.csv"

In [89]:
test_file_path=r"C:\Sensor-Fault-Detection\artifact\07_29_2024_15_02_42\data_ingestion\ingested\test.csv"

In [90]:
pd.read_csv(test_file_path)

class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0      neg      26     NaN    10.0    10.0     0.0     0.0     0.0     0.0   
1      neg       8     2.0    20.0    20.0     0.0     0.0     0.0     0.0   
2      neg   31048     NaN   836.0   750.0     0.0     0.0     0.0     0.0   
3      neg   29068     NaN   200.0   192.0     0.0     0.0     0.0     0.0   
4      neg   59854     NaN   270.0   242.0     0.0     0.0     0.0     0.0   
...    ...     ...     ...     ...     ...     ...     ...     ...     ...   
7233   neg     260     2.0    18.0    10.0     0.0     0.0     0.0     0.0   
7234   neg   79636     NaN     0.0     0.0     0.0     0.0     0.0     0.0   
7235   neg      12     0.0    52.0     NaN     0.0     0.0     0.0     0.0   
7236   neg   40266     NaN   126.0   120.0     0.0     0.0     0.0     0.0   
7237   neg     394     NaN   174.0   128.0     0.0     0.0     0.0     0.0   

      ag_002  ...    ee_002    ee_003    ee_004    ee_005    ee_006    ee_007  \
0        0.0  ...     458.0      74.0       8.0       0.0       0.0       0.0   
1        0.0  ...      64.0      40.0     106.0      10.0       0.0       0.0   
2        0.0  ...  313492.0  142288.0  403858.0  332090.0  175416.0   49998.0   
3        0.0  ...  220390.0  116152.0  270792.0  273338.0  218166.0  160792.0   
4        0.0  ...  488870.0  223824.0  396000.0  334808.0  298706.0  251392.0   
...      ...  ...       ...       ...       ...       ...       ...       ...   
7233   924.0  ...    3396.0     974.0    2062.0    1844.0    1380.0    1084.0   
7234     0.0  ...  806832.0  449962.0  778826.0  581558.0  375498.0  222866.0   
7235     0.0  ...     222.0      46.0      68.0      22.0       0.0       0.0   
7236     0.0  ...  371424.0  177656.0  375346.0  354272.0  349192.0   77016.0   
7237     0.0  ...    3476.0    1266.0    1844.0     878.0     710.0    8426.0   

        ee_008   ee_009  ef_000  eg_000  
0          0.0      0.0     0.0     0.0  
1          0.0      0.0     0.0     0.0  
2       9562.0      0.0     0.0     0.0  
3      32812.0      0.0     0.0     0.0  
4     558374.0  21694.0     0.0     0.0  
...        ...      ...     ...     ...  
7233       0.0      0.0     0.0     0.0  
7234  358934.0  19548.0     0.0     0.0  
7235       0.0      0.0     0.0     0.0  
7236  106296.0   4524.0     0.0     0.0  
7237      76.0      0.0     0.0     0.0  

[7238 rows x 171 columns]

In [91]:
train_df = pd.read_csv(training_file_paTH) 
test_df = pd.read_csv(test_file_path)

In [92]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [93]:
test_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [94]:
d1 = train_df['aa_000']
d2 = test_df['aa_000']

In [95]:
ks_2samp(d1,d2)

KstestResult(statistic=np.float64(0.008798926792532802), pvalue=np.float64(0.7576754766408167), statistic_location=np.int64(3508), statistic_sign=np.int8(1))

In [96]:
d1 = train_df['class']
d2 = test_df['class'] 

In [97]:
ks_2samp(d1,d2)

KstestResult(statistic=np.float64(0.0013797072732141258), pvalue=np.float64(1.0), statistic_location='neg', statistic_sign=np.int8(1))

In [107]:
report ={} 
def get_drift_report(train_df,test_df,threshold=0.5):
    for column in train_df.columns:
        d1 = train_df[column]
        d2 = test_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=is_same_dist.pvalue:
            is_found = False 
        else:
            is_found = True
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            }}) 
    return report

In [99]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [100]:
test1 = ks_2samp(train_df['ac_000'],test_df['ac_000'])

In [101]:
test1.pvalue

np.float64(nan)

In [108]:
get_drift_report(train_df,test_df)

{'class': {'p_value': 1.0, 'drift_status': False},
 'aa_000': {'p_value': 0.7576754766408167, 'drift_status': False},
 'ab_000': {'p_value': nan, 'drift_status': True},
 'ac_000': {'p_value': nan, 'drift_status': True},
 'ad_000': {'p_value': nan, 'drift_status': True},
 'ae_000': {'p_value': nan, 'drift_status': True},
 'af_000': {'p_value': nan, 'drift_status': True},
 'ag_000': {'p_value': nan, 'drift_status': True},
 'ag_001': {'p_value': nan, 'drift_status': True},
 'ag_002': {'p_value': nan, 'drift_status': True},
 'ag_003': {'p_value': nan, 'drift_status': True},
 'ag_004': {'p_value': nan, 'drift_status': True},
 'ag_005': {'p_value': nan, 'drift_status': True},
 'ag_006': {'p_value': nan, 'drift_status': True},
 'ag_007': {'p_value': nan, 'drift_status': True},
 'ag_008': {'p_value': nan, 'drift_status': True},
 'ag_009': {'p_value': nan, 'drift_status': True},
 'ah_000': {'p_value': nan, 'drift_status': True},
 'ai_000': {'p_value': nan, 'drift_status': True},
 'aj_000': {'p_

In [82]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [58]:
test_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [59]:
2==2

True

In [81]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [87]:
ks_2samp(train_df['ad_000'],test_df['ad_000'])

KstestResult(statistic=np.float64(nan), pvalue=np.float64(nan), statistic_location=np.float64(nan), statistic_sign=np.float64(nan))

In [85]:
train_df.head()

class  aa_000  ab_000        ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0   neg   58244     NaN  2.920000e+03  2656.0     0.0     0.0     0.0     0.0   
1   neg      88     0.0  2.130706e+09    24.0     0.0     0.0     0.0     0.0   
2   neg   58350     NaN  2.060000e+02   150.0     0.0     0.0     0.0     0.0   
3   neg   28896     NaN  2.778000e+03  2494.0     0.0     0.0     0.0     0.0   
4   neg   20446     NaN  1.500000e+03     NaN     0.0     0.0     0.0     0.0   

   ag_002  ...    ee_002    ee_003    ee_004    ee_005    ee_006    ee_007  \
0     0.0  ...  809974.0  318132.0  817308.0  193242.0  288472.0  331198.0   
1     0.0  ...    1914.0     818.0    1188.0      44.0      90.0      10.0   
2     0.0  ...  244760.0  126708.0  292808.0  394588.0  455312.0  370274.0   
3     0.0  ...  388996.0  213406.0  386426.0   31884.0     344.0       4.0   
4     0.0  ...  131104.0   60438.0  119634.0  136708.0   67956.0   52774.0   

     ee_008   ee_009  ef_000  eg_000  
0    3016.0      0.0     0.0     0.0  
1       0.0      0.0     0.0     0.0  
2  555652.0  18992.0     0.0     0.0  
3       0.0      0.0     0.0     0.0  
4  205720.0  44412.0     0.0     0.0  

[5 rows x 171 columns]

In [86]:
test_df.head()

class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0   neg    1114     0.0     0.0    24.0     0.0     0.0     0.0     0.0   
1   neg     232     NaN    38.0    36.0     0.0     0.0     0.0     0.0   
2   neg     810     NaN    48.0     0.0     0.0     0.0     0.0     0.0   
3   neg     226     NaN    50.0    18.0     0.0     0.0     0.0     0.0   
4   neg    1208     NaN    16.0    12.0     0.0     0.0     0.0     0.0   

   ag_002  ...  ee_002  ee_003  ee_004  ee_005   ee_006  ee_007  ee_008  \
0     0.0  ...     0.0     0.0     0.0     0.0      0.0     0.0     0.0   
1     0.0  ...  2278.0   452.0  1388.0  1618.0    736.0  1938.0     0.0   
2     0.0  ...  6118.0  2138.0  5584.0  9304.0  10878.0  1400.0    12.0   
3     0.0  ...  1622.0   454.0   488.0  1036.0   1188.0  3792.0     0.0   
4     0.0  ...  8866.0  2864.0  9394.0  5178.0  16944.0  4046.0    16.0   

   ee_009  ef_000  eg_000  
0     0.0     0.0     0.0  
1     0.0     0.0     0.0  
2     0.0     0.0     0.0  
3     0.0     0.0     0.0  
4     0.0     0.0     0.0  

[5 rows x 171 columns]

In [103]:
from sensor.utils.main_utils import write_yaml_file

In [109]:
drift_report = get_drift_report(train_df,test_df)

In [105]:
import os 

In [110]:
write_yaml_file(file_path=os.path.join(os.getcwd(),'reort.yaml'),content=drift_report)